<a href="https://colab.research.google.com/github/drraju/TFCertifiedIn100Days/blob/main/Day_1__4th_March_22_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Day 1 - Challeng to https://www.udemy.com/course/tensorflow-developer-certificate-machine-learning-zero-to-mastery (Daniel Bourke Udemy Course) by 25th March 2022**

Date: 4th March 2022

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In this notebook, we will cover some of the fundamental concepts of tensors using TensorFlow

Topics:
* Introduction to Tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* using @tf.function ( a way to speed up regular python functions)
* using GPU with TF (or TPUs)
* Excercises to try

### Introduction to Tensors

In [ ]:
 # import tensorflow
 import tensorflow as tf
 print(tf.__version__) # Prints the version of tensorflow

2.8.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions (ndim) of a tensor
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix 
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let us create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                       [10,11,12]],
                       [[13, 14, 15],
                        [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

0-dimensional tensor is scalar(a single number), 1-dimensional tensor is vector(a number with direction like wind speed etc), 2-dimensional tensor is matrix (2d array of numbers)

### Tensorflow Variable

tf.Variable


tf.Variable(
    initial_value=None, trainable=None, validate_shape=True, caching_device=None,
    name=None, variable_def=None, dtype=None, import_scope=None, constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE, shape=None
)


In [ ]:
# Create tensors using tf.Variable.
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# change one of the elements in changeable tensor <<The following gives error as shown in text below
#changeable_tensor[0] = 7

TypeError                                 Traceback (most recent call last)
<ipython-input-13-263e66d04580> in <module>()
      1 # change one of the elements in changeable tensor
----> 2 changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# try using .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensors

Random tensors are tensors of arbitory nature 

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) 
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffling the order of elements in a tensor

In [ ]:
# shuffle a tensor
not_shuffled = tf.constant([[10,7],
                             [3,4],
                             [2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Some Examples from Youtube Tensorflow Introduction