<a href="https://colab.research.google.com/github/drraju/TFCertifiedIn100Days/blob/main/Day_3_6th_March_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Continuing Section 2 DL and TF fundamentals from TF Developer Certificate in 2022

In [1]:
# Indexing and Expanding Tensors

In [3]:
import tensorflow as tf
import numpy as np

In [4]:
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [5]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimens (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor", tf.size(rank_4_tensor))
print("Total number of elements in our tensor", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimens (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor 120


## Indexing tensors

Tensors can be indexed just like Python lists

In [10]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [13]:
# Get first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :] 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [14]:
# Create a rank 2 tensor (2 dimesions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [15]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [16]:
# Get the last item of each of row or our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [19]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # Every access before new one use ...

In [20]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [21]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [23]:
tf.expand_dims(rank_2_tensor, axis=0)  # Expand -0 access

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulating Tensors with basic operations

In [24]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [25]:
# Basic Operations

In [26]:
# Add value to a tensor using addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [27]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [28]:
# Multiplication
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

In [30]:
# we can use tensorflow built=in functions too
tf.multiply(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

## Matrix Multiplication

In ML, matrix operations are commonly used

In [31]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [32]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [34]:
# Matrix Multiplication with Python operator "*"
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [37]:
tensor_1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor_1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [38]:
tensor_2 = tf.constant([[3,5],[6,7],[1,8]])

In [39]:
tensor_1, tensor_2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [41]:
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [42]:
tensor_1.shape, tensor_2.shape

(TensorShape([3, 3]), TensorShape([3, 2]))

In [43]:
tf.matmul(tensor_2, tensor_1)

InvalidArgumentError: ignored

In [48]:
tensor_1 @ tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [54]:
tensor_2 * tf.transpose(tensor_1)

InvalidArgumentError: ignored

In [55]:
# Change the shape
tf.reshape(tensor_2, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [61]:
tensor_1.shape, tensor_2.shape

(TensorShape([3, 3]), TensorShape([3, 2]))

In [60]:
tf.matmul(tensor_2, tf.reshape(tensor_1, shape=(2,3)))

InvalidArgumentError: ignored

In [67]:
tensor_4 = tf.reshape(tensor_2, shape=(2,3))

In [68]:
tensor_4

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [69]:
tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [72]:
tensor_2 * tf.reshape(tensor_4, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9, 25],
       [36, 49],
       [ 1, 64]], dtype=int32)>

In [73]:
# Can do the same with transpose
tf.transpose(tensor_4)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 7],
       [5, 1],
       [6, 8]], dtype=int32)>

In [75]:
 tf.reshape(tensor_4, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

### The Dot product

* 'tf.matmul()'
* 'tf.tensordot()'
* '@'

In [78]:
# Perform the dot product on tensor_1 and tensor_2
tf.tensordot(tensor_1, tensor_2, axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [79]:
tf.tensordot(tensor_1, tensor_2, axes=0)

<tf.Tensor: shape=(3, 3, 3, 2), dtype=int32, numpy=
array([[[[ 3,  5],
         [ 6,  7],
         [ 1,  8]],

        [[ 6, 10],
         [12, 14],
         [ 2, 16]],

        [[15, 25],
         [30, 35],
         [ 5, 40]]],


       [[[21, 35],
         [42, 49],
         [ 7, 56]],

        [[ 6, 10],
         [12, 14],
         [ 2, 16]],

        [[ 3,  5],
         [ 6,  7],
         [ 1,  8]]],


       [[[ 9, 15],
         [18, 21],
         [ 3, 24]],

        [[ 9, 15],
         [18, 21],
         [ 3, 24]],

        [[ 9, 15],
         [18, 21],
         [ 3, 24]]]], dtype=int32)>

### Changing the datatype of a tensor

In [80]:
# Create a new tensor with default data type
B = tf.constant([1.7, 7.3])
B.dtype

tf.float32

In [82]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [84]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.3], dtype=float16)>,
 tf.float16)

### Aggregating Tensors

Aggregating tensors means condensing them from multiple values down to a smaller amount of values

In [85]:
# GEt the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [86]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Let us go through the following forms of aggregation

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [87]:
# create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([90, 88, 89, 43, 25, 10,  5, 72, 74, 15, 71, 25, 99,  2, 69, 10, 12,
       80,  5, 72, 88, 30, 20, 44, 54, 64, 31, 45, 86, 20, 96, 14, 15, 56,
       27, 91, 79, 74, 97,  8,  1, 68, 12, 43, 54, 37, 41, 77, 35, 66])>

In [89]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [90]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [91]:
# Find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [92]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [93]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2429>

In [100]:
import tensorflow_probability as tfp

In [101]:
# Find the variance
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=943>

In [107]:
# Find the standard deviation
tfp.stats.stddev(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.716177>

In [103]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.716177>

In [109]:
# positional max
tf.math.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [110]:
# positional min
tf.math.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=40>

In [111]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [112]:
tf.math.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [113]:
tf.math.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [114]:
# index on largest value position
F[tf.math.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [115]:
F[tf.math.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [117]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [118]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)


In [119]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [120]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [121]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>, TensorShape([50]))

### One Hot Encoding

In [122]:
# Create a list of indices
some_list = [0,1,2,3] 

# one hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [126]:
# Specifying custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value='Yo', off_value="I too")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yo', b'I too', b'I too', b'I too'],
       [b'I too', b'Yo', b'I too', b'I too'],
       [b'I too', b'I too', b'Yo', b'I too'],
       [b'I too', b'I too', b'I too', b'Yo']], dtype=object)>

### Squaring, log, square

In [127]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [128]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [132]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [135]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>